
name: Publish Preview

on:
  push:
    tags: ["*"]

permissions:
  pull-requests: write
  contents: write


jobs:

  version:
    runs-on: windows-latest
    outputs:
      version: ${{ github.ref_name }}
    steps:
      - name: Version
        run: Write-Host "publish version is ${{ github.ref_name }}" -Foreground Green


  build:
    runs-on: windows-latest
    needs: version
    outputs:
      version: ${{ needs.version.outputs.version }}
    strategy:
      matrix:
        platform: [x64, arm64]
    env:
      Platform: ${{ matrix.platform }}
      Version: ${{ needs.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: SHA
        id: sha
        run: echo "sha=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_OUTPUT
    
      - name: Restore NuGet Packages
        run: dotnet restore NonsPlayer
        
      - name: Build
        run: $sha = "${{ steps.sha.outputs.sha }}"
          New-Item -Path "build/NonsPlayer/" -Type Directory
          msbuild NonsPlayer.Launcher "-property:Configuration=$env:Configuration;Platform=$env:Platform;OutDir=$(Resolve-Path "build/NonsPlayer/")"
          dotnet build NonsPlayer -c $env:Configuration -o "build/NonsPlayer/app-build.$sha" -p:Platform=$env:Platform -p:Version="0.0.1-build.$sha" -p:DefineConstants=CI
          Add-Content "build/NonsPlayer/version.ini" -Value "app_folder=app-build.$sha`r`nexe_name=NonsPlayer.exe"
          Remove-Item "build/NonsPlayer/NonsPlayer.pdb" -Force

      - name: Metadata
        run: ./metadata.ps1 -Architecture $env:Platform -Version $env:Version

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: metadata_${{ matrix.platform }}
          path: build/metadata/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          files: ./build/release/package/*


  metadata:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout Metadata
        uses: actions/checkout@v3
        with:
          ref: metadata

      - name: Download Artifact x64
        uses: actions/download-artifact@v3.0.2
        with:
          name: metadata_x64

      - name: Download Artifact arm64
        uses: actions/download-artifact@v3.0.2
        with:
          name: metadata_arm64

      - name: Create Metadata Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-metadata/v1
          delete-branch: true
          title: update metadata ${{ needs.build.outputs.version }}
          commit-message: update metadata ${{ needs.build.outputs.version }}

